Firewall executor
crypto-pepe/firewall pull request #16
Opened 2022-05-06 14:36 UTC by hehegrrrhehegrr

2022-05-06 15:41 UTC, stuffy-idler requested changes

2022-05-06 15:41 UTC, stuffy-idler commented on .gitignore
> +/.vscode
Add newline at the end of all files, it's common best practise

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/Cargo.toml
> +tokio = { version = "*", features = ["full"] }
Tokio docs describes all of its features. Please, specify used  only

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/config.yaml
> +  conn_string: 'redis://127.0.0.1:6379'
It's better to build conn string at the code, but not providing it via config.

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/model.rs
> +impl Debug for TargetType {
I think `Debug` deriving can give the same result and I suggest to use it.
If you want to update case of values while serialize/deserialize, you can specify `#[serde(rename_all = "snake_case")]` for entire struct

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/model.rs
> +    #[serde(rename = "value")]
It's excess, `value` is already `value`

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/main.rs
> +        App::new()
Let's move it to separate module with its child (process_ban)

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/main.rs
> +    for bt in &ban.target{
Your purpose here is to transform `ban.target` to list of futures, so you can do it using `map`

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/main.rs
> +        handles.push(tokio::spawn(async move {
It doesn't needed to do value fetching at separate thread, let's make it simpler with a basic future

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/main.rs
> +                Err(e) => {error!(""); return Err(e.to_string())}
You have an error `e`, so you can print it. Empty string is not descriptive what is problem, try not to do things like this one

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/main.rs
> +            let mut conn = match pool.get().await {
If you are not going to do anything with value from future, but to do smth with an error, it's better to:
```rust
let mut conn = match pool.get().await.map_err(|e| {
  error!("{:?}", e);
  Err(e.to_string())
})?;

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/main.rs
> +            match cmd("HSET").arg(&key).arg(anl).arg(reason).query_async(&mut *conn).await
In this case you are not doing anything with future result, only err, so you can do:
```rust
cmd("HSET")
  .arg(&key)
  .arg(anl)
  .arg(reason)
  .query_async(&mut *conn)
  .await
  .map_err(|re| re.to_string())?;
```

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/main.rs
> +            match cmd("EXPIRE").arg(&key).arg(ttl).arg("GT")
The same notice as above

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/main.rs
> +    for res in join_all(handles).await {
Rewrite it using combinators, it will be more readable and supportable

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/main.rs
> +    let rcm = match RedisConnectionManager::new(cfg.redis.conn_string.to_string()) {
Let's move redis pool initialization to separate module

2022-05-06 15:41 UTC, stuffy-idler commented on firewall_redis/src/config.rs
> +    #[serde(rename(deserialize = "redis"))]
It does not need to be renamed (`server` too)

2022-05-11 13:42 UTC, hehegrrrhehegrr commented on firewall_redis/src/main.rs
> +    for res in join_all(handles).await {
Tried to put everything into one combinator, looked cumbersome and unreadable, so let's keep it as it is now - 2 separate combinators.

2022-05-11 14:51 UTC, stuffy-idler requested changes

2022-05-12 09:16 UTC, stuffy-idler requested changes

2022-05-12 09:16 UTC, stuffy-idler commented on firewall_redis/src/redis.rs
> +    pub async fn new<'a>(cfg: &Config) -> Result<Self, String> {
Return `String` is not informative, better to return concrete Error.
There is best practice to do this: create `enum Error` with derived `thiserror::Error` with all of failing cases, and use it as with `Result`:
```rust
use error::Error as AppError;

// ...

pub async fn new<'a>(cfg: &Config) -> Result<Self, AppError> {
  // ...
}

// match bb8::Pool::builder().build(rcm).await {
//   Err(e) => Err(format!("build pool: {:?}", e.to_string())),
//   Ok(p) => Ok(p),
// }

bb8::Pool::builder()
  .build(rcm)
  .await
  .map_err(|err| AppError::Bb8PoolBuild(err))
```

2022-05-12 09:16 UTC, stuffy-idler commented on firewall_redis/src/server.rs
> +fn configure(cfg: &mut web::ServiceConfig, red: redis::Service) {
Mutating is not true rust way to write the code. It's better to create new instance of smth from provided data

2022-05-13 08:32 UTC, closed without merging