prepare data
crypto-pepe/firewall pull request #17
Opened 2022-05-11 07:05 UTC by lynxbyorion

2022-05-11 08:50 UTC, stuffy-idler requested changes

2022-05-11 08:50 UTC, stuffy-idler commented on collector/config.yaml
> +  chunk_size: 1024
Two other parameters called as `max_<smth>`, maybe this one should be called by analogy?

2022-05-11 08:50 UTC, stuffy-idler commented on collector/src/main.rs
> +    let (sender, reciver) = mpsc::channel::<store::Request>(32);
Mistype: missing `e` in the `receiver`

2022-05-11 08:50 UTC, stuffy-idler commented on collector/src/main.rs
> +            .app_data(data.clone())
Is it necessary `data` to be cloned?

2022-05-11 08:50 UTC, stuffy-idler commented on collector/src/main.rs
>          return "NOT OK";
Let's add logging for this case, I think `warn` should be suitable

2022-05-11 08:50 UTC, stuffy-idler commented on collector/src/main.rs
> +                        x.0.to_string(),
I suggest to destructarize `x` at closure parameters with appropriate names

2022-05-11 08:50 UTC, stuffy-idler commented on collector/src/main.rs
> +        delay.reset();
Whether path `_ = delay.tick()` is reachable with resetting interval at each loop iteration if the receiver will receive messages more often then `max_collect_chunk_duration`?

2022-05-11 08:50 UTC, stuffy-idler commented on collector/src/store.rs
> +use deepsize::DeepSizeOf;
Let's add tests for the methods in this module

2022-05-11 12:13 UTC, lynxbyorion commented on collector/src/store.rs
> +use deepsize::DeepSizeOf;
Add tests in the next issue. Because Kafka sender is desable.

2022-05-11 12:13 UTC, lynxbyorion commented on collector/src/main.rs
> +    let (sender, reciver) = mpsc::channel::<store::Request>(32);
fixed

2022-05-11 12:13 UTC, lynxbyorion commented on collector/src/main.rs
> +            .app_data(data.clone())
Seem to be. Closures are lazy, we do not know the lifetime of the variables in them.

2022-05-11 12:13 UTC, lynxbyorion commented on collector/src/main.rs
>          return "NOT OK";
Fixed

2022-05-11 12:13 UTC, lynxbyorion commented on collector/src/main.rs
> +                        x.0.to_string(),
I agree. Fixed.

2022-05-11 12:13 UTC, lynxbyorion commented on collector/src/main.rs
> +        delay.reset();
hmm. It's wrong logic. Fixed.

2022-05-12 07:34 UTC, stuffy-idler commented on collector/src/store.rs
> +use deepsize::DeepSizeOf;
Got it. Ok

2022-05-12 07:36 UTC, stuffy-idler approved these changes

2022-05-12 07:41 UTC, merged